'use strict';

const FILE_MAGIC = Buffer.from('MTDB');
const RECORD_MAGIC = Buffer.from('MTR1');

const VERSION = 2;
const HEADER_SIZE = 4096;

const HEADER_STATE_OFFSET = 12;

const HEADER_STATES = Object.freeze({
  CLEAN: 0,
  DIRTY: 1
});

const BUCKET_COUNT = 65536;
const BUCKET_SIZE = 8;
const INDEX_OFFSET = HEADER_SIZE;
const DATA_OFFSET = INDEX_OFFSET + BUCKET_COUNT * BUCKET_SIZE;
const RECORD_HEADER_SIZE = 32;
const MAX_PATH_LENGTH = 1024;
const MAX_JSON_SIZE = 100 * 1024 * 1024;

const RECORD_TYPES = Object.freeze({
  DIRECTORY: 1,
  WRITE: 2,
  DELETE: 3,
  COMMIT: 4
});

module.exports = {
  FILE_MAGIC,
  RECORD_MAGIC,
  VERSION,
  HEADER_SIZE,
  BUCKET_COUNT,
  BUCKET_SIZE,
  INDEX_OFFSET,
  DATA_OFFSET,
  RECORD_HEADER_SIZE,
  MAX_PATH_LENGTH,
  MAX_JSON_SIZE,
  HEADER_STATE_OFFSET,
  HEADER_STATES,
  RECORD_TYPES
};